version: '2'
services:
    public:
        container_name: "week4-public"
        build:
            context: .
            dockerfile: Dockerfile_public
        ports:
            - "12303:80"
        volumes:
            - "./public:/var/www/html"
        networks:
            default:
                ipv4_address: 172.21.0.31
        extra_hosts:
            - "hgame-private:172.21.0.76"    

    private:
        container_name: "week4-private"
        build: 
            context: .
            dockerfile: Dockerfile_private
        volumes:
            - "./private:/var/www/html"
        networks:
            default:
                ipv4_address: 172.21.0.76
        extra_hosts:
            - "checker:172.21.0.236"

    check:
        container_name: "token-checker"
        build:
            context: .
            dockerfile: Dockerfile_checker
        volumes:
        - "./checker:/var/www/html"
        networks:
            default:
                ipv4_address: 172.21.0.236

networks:
    default:
        external:
            name: docker-br0
